# Generated by Django 2.2.5 on 2021-03-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('severity', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('vul_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Vulnerability')),
            ],
            options={
                'db_table': 'dates',
            },
        ),
    ]
