# Generated by Django 2.2.5 on 2021-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
