# Generated by Django 2.2.5 on 2021-03-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210318_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='vul_id',
            new_name='vuln_id',
        ),
    ]
