# Generated by Django 2.2.5 on 2021-03-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20210318_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='vuln_id',
            new_name='vuln',
        ),
    ]
